### PR TITLE
upgraded to mobx v3, mobx-react v4, added mobx-react-router

### LINKED ISSUE #41: How to use RouterStore
On some occasions I want to have an opportunity to push a route.  Normally I would do it with injecting routing store. for example

```

@inject('routing') @observer
export default class Home extends Component {

  render() {
    let {routing} = this.props;
    return (
      <button onClick={()=>routing.push('/path/to/go')}>Push it</button>
    )
  }
```

But to have this work I have to configure it like this
```
import {Router} from "react-router-dom";
import createBrowserHistory from 'history/createBrowserHistory';
import {RouterStore, syncHistoryWithStore} from 'mobx-react-router';

const renderApp = () => {
  const browserHistory = createBrowserHistory();
  const routeStore = new RouterStore();
  const history = syncHistoryWithStore(browserHistory, routeStore);
  render(
    <AppContainer>
      <Provider store={store} routing={routeStore}>
        <Router history={history}>
          <App />
        </Router>
      </Provider>
    </AppContainer>,
    document.getElementById("root")
  );
};

``` 

I expect it work

```
 render() {
    let {routing} = this.props;
    return (
      <div >
        <Switch>
          <Route exact path="/" render={props => (
            <LazyRoute {...props} component={import("../pages/Home")}/>
          )}/>
         <Route exact path="/path/to/go" render={props => (
            <LazyRoute {...props} component={import("../pages/OtherPage")}/>
          )}/>
       </Switch>
     </div>
    )
}
```

Location change on address bar but OtherPage does not render until I do some thing like this:
```
 render() {
    let {routing} = this.props;
    return (
      <div >
        <span style={{display: 'none'}}>{routing.location.pathname}</span>
        <Switch>
          <Route exact path="/" render={props => (
            <LazyRoute {...props} component={import("../pages/Home")}/>
          )}/>
         <Route exact path="/path/to/go" render={props => (
            <LazyRoute {...props} component={import("../pages/OtherPage")}/>
          )}/>
       </Switch>
     </div>
    )
}
```

Am I doing something wrong? I feel I'm missing something

### PR DESCRIPTION
**Pull request by jaynakus**
I had upgraded to mobx 3.

There is still a weird problem. When pressing browsers back button does not re-render immediately. Probably a problem with mobx-react-router lib, will have to write an issue there.
 
Closes #41

### CODE REVIEW

**Comment by njleonzhang** [comment]
@jaynakus can this config work? have you fixed the issue you mentioned?

**Comment by jaynakus** [comment]
@njleonzhang, see the last commit, I had solved the problem the other way.

**Comment by njleonzhang** [comment]
@jaynakus tnx, I have also make it works. I am a newbie, what `rfx-core` does? do we always need it?

**Comment by njleonzhang** [comment]
@jaynakus I have tried your solution, but after triggering any hot-reload, router can not work. 
 
image

**Comment by jaynakus** [comment]
@njleonzhang, everything works as it should, you'll have to live with that warning, because hot reloading is all about hacking.

**Pull request closed without merging**
